import { GameCategory, CategoryId } from './types';

export const GAME_CATEGORIES: Record<CategoryId, GameCategory> = {
  sport: {
    id: 'sport',
    label: 'Sport',
    questionPhrase: 'What sport do you like?',
    answerPhraseTemplate: 'I like {option}!',
    icon: '⚽',
    options: [
      { id: 'soccer', keyNumber: 1, name: 'Soccer', icon: '⚽', colorClass: 'bg-emerald-500', phonetic: '/ˈsɒk.ər/' },
      { id: 'basketball', keyNumber: 2, name: 'Basketball', icon: '🏀', colorClass: 'bg-orange-500', phonetic: '/ˈbæs.kɪt.bɔːl/' },
      { id: 'swimming', keyNumber: 3, name: 'Swimming', icon: '🏊‍♂️', colorClass: 'bg-sky-500', phonetic: '/ˈswɪm.ɪŋ/' },
      { id: 'baseball', keyNumber: 4, name: 'Baseball', icon: '⚾', colorClass: 'bg-amber-600', phonetic: '/ˈbeɪs.bɔːl/' },
      { id: 'tennis', keyNumber: 5, name: 'Tennis', icon: '🎾', colorClass: 'bg-lime-500', phonetic: '/ˈten.ɪs/' },
      { id: 'badminton', keyNumber: 6, name: 'Badminton', icon: '🏸', colorClass: 'bg-purple-500', phonetic: '/ˈbæd.mɪn.tən/' },
    ],
  },
  color: {
    id: 'color',
    label: 'Color',
    questionPhrase: 'What color do you like?',
    answerPhraseTemplate: 'I like {option}!',
    icon: '🎨',
    options: [
      { id: 'blue', keyNumber: 1, name: 'Blue', icon: '🔵', colorClass: 'bg-blue-600', phonetic: '/bluː/' },
      { id: 'red', keyNumber: 2, name: 'Red', icon: '🔴', colorClass: 'bg-red-600', phonetic: '/red/' },
      { id: 'green', keyNumber: 3, name: 'Green', icon: '🟢', colorClass: 'bg-green-600', phonetic: '/ɡriːn/' },
      { id: 'yellow', keyNumber: 4, name: 'Yellow', icon: '🟡', colorClass: 'bg-yellow-500', phonetic: '/ˈjel.oʊ/' },
      { id: 'purple', keyNumber: 5, name: 'Purple', icon: '🟣', colorClass: 'bg-purple-600', phonetic: '/ˈpɜːr.pəl/' },
      { id: 'orange', keyNumber: 6, name: 'Orange', icon: '🟠', colorClass: 'bg-orange-500', phonetic: '/ˈɒr.ɪndʒ/' },
    ],
  },
  fruit: {
    id: 'fruit',
    label: 'Fruit',
    questionPhrase: 'What fruit do you like?',
    answerPhraseTemplate: 'I like {option}!',
    icon: '🍎',
    options: [
      { id: 'apples', keyNumber: 1, name: 'Apples', icon: '🍎', colorClass: 'bg-red-500', phonetic: '/ˈæp.əlz/' },
      { id: 'bananas', keyNumber: 2, name: 'Bananas', icon: '🍌', colorClass: 'bg-yellow-400', phonetic: '/bəˈnæn.əz/' },
      { id: 'strawberries', keyNumber: 3, name: 'Strawberries', icon: '🍓', colorClass: 'bg-rose-500', phonetic: '/ˈstrɔː.ber.iz/' },
      { id: 'watermelon', keyNumber: 4, name: 'Watermelon', icon: '🍉', colorClass: 'bg-emerald-600', phonetic: '/ˈwɔː.təˌmel.ən/' },
      { id: 'grapes', keyNumber: 5, name: 'Grapes', icon: '🍇', colorClass: 'bg-indigo-500', phonetic: '/ɡreɪps/' },
      { id: 'oranges', keyNumber: 6, name: 'Oranges', icon: '🍊', colorClass: 'bg-amber-500', phonetic: '/ˈɒr.ɪn.dʒɪz/' },
    ],
  },
  food: {
    id: 'food',
    label: 'Food',
    questionPhrase: 'What food do you like?',
    answerPhraseTemplate: 'I like {option}!',
    icon: '🍕',
    options: [
      { id: 'pizza', keyNumber: 1, name: 'Pizza', icon: '🍕', colorClass: 'bg-amber-600', phonetic: '/ˈpiːt.sə/' },
      { id: 'hamburgers', keyNumber: 2, name: 'Hamburgers', icon: '🍔', colorClass: 'bg-orange-600', phonetic: '/ˈhæmˌbɜːr.ɡərz/' },
      { id: 'sushi', keyNumber: 3, name: 'Sushi', icon: '🍣', colorClass: 'bg-teal-600', phonetic: '/ˈsuː.ʃi/' },
      { id: 'ramen', keyNumber: 4, name: 'Ramen', icon: '🍜', colorClass: 'bg-red-600', phonetic: '/ˈrɑː.mən/' },
      { id: 'tacos', keyNumber: 5, name: 'Tacos', icon: '🌮', colorClass: 'bg-yellow-600', phonetic: '/ˈtɑː.koʊz/' },
      { id: 'curry', keyNumber: 6, name: 'Curry Rice', icon: '🍛', colorClass: 'bg-amber-700', phonetic: '/ˈkɜːr.i raɪs/' },
    ],
  },
  drink: {
    id: 'drink',
    label: 'Drink',
    questionPhrase: 'What drink do you like?',
    answerPhraseTemplate: 'I like {option}!',
    icon: '🧋',
    options: [
      { id: 'boba', keyNumber: 1, name: 'Boba Milk Tea', icon: '🧋', colorClass: 'bg-amber-700', phonetic: '/ˈboʊ.bə mɪlk tiː/' },
      { id: 'hot_chocolate', keyNumber: 2, name: 'Hot Chocolate', icon: '☕', colorClass: 'bg-stone-700', phonetic: '/hɒt ˈtʃɒk.lət/' },
      { id: 'orange_juice', keyNumber: 3, name: 'Orange Juice', icon: '🧃', colorClass: 'bg-orange-500', phonetic: '/ˈɒr.ɪndʒ dʒuːs/' },
      { id: 'soda', keyNumber: 4, name: 'Soda', icon: '🥤', colorClass: 'bg-rose-600', phonetic: '/ˈsoʊ.də/' },
      { id: 'lemonade', keyNumber: 5, name: 'Lemonade', icon: '🍋', colorClass: 'bg-yellow-500', phonetic: '/ˌlem.əˈneɪd/' },
      { id: 'milkshake', keyNumber: 6, name: 'Milkshake', icon: '🥛', colorClass: 'bg-pink-500', phonetic: '/ˈmɪlk.ʃeɪk/' },
    ],
  },
  dessert: {
    id: 'dessert',
    label: 'Dessert',
    questionPhrase: 'What dessert do you like?',
    answerPhraseTemplate: 'I like {option}!',
    icon: '🍨',
    options: [
      { id: 'ice_cream', keyNumber: 1, name: 'Ice Cream', icon: '🍨', colorClass: 'bg-cyan-600', phonetic: '/ˈaɪs ˌkriːm/' },
      { id: 'chocolate_cake', keyNumber: 2, name: 'Chocolate Cake', icon: '🍰', colorClass: 'bg-amber-800', phonetic: '/ˈtʃɒk.lət keɪk/' },
      { id: 'donuts', keyNumber: 3, name: 'Donuts', icon: '🍩', colorClass: 'bg-pink-600', phonetic: '/ˈdoʊ.nʌts/' },
      { id: 'cookies', keyNumber: 4, name: 'Cookies', icon: '🍪', colorClass: 'bg-amber-600', phonetic: '/ˈkʊk.iz/' },
      { id: 'pudding', keyNumber: 5, name: 'Pudding', icon: '🍮', colorClass: 'bg-yellow-600', phonetic: '/ˈpʊd.ɪŋ/' },
      { id: 'waffles', keyNumber: 6, name: 'Waffles', icon: '🧇', colorClass: 'bg-amber-500', phonetic: '/ˈwɒf.əlz/' },
    ],
  },
  animal: {
    id: 'animal',
    label: 'Animal',
    questionPhrase: 'What animal do you like?',
    answerPhraseTemplate: 'I like {option}!',
    icon: '🐼',
    options: [
      { id: 'dogs', keyNumber: 1, name: 'Dogs', icon: '🐶', colorClass: 'bg-amber-600', phonetic: '/dɒɡz/' },
      { id: 'cats', keyNumber: 2, name: 'Cats', icon: '🐱', colorClass: 'bg-orange-500', phonetic: '/kæts/' },
      { id: 'pandas', keyNumber: 3, name: 'Pandas', icon: '🐼', colorClass: 'bg-zinc-800', phonetic: '/ˈpæn.dəz/' },
      { id: 'lions', keyNumber: 4, name: 'Lions', icon: '🦁', colorClass: 'bg-yellow-600', phonetic: '/ˈlaɪ.ənz/' },
      { id: 'dolphins', keyNumber: 5, name: 'Dolphins', icon: '🐬', colorClass: 'bg-cyan-600', phonetic: '/ˈdɒl.fɪnz/' },
      { id: 'koalas', keyNumber: 6, name: 'Koalas', icon: '🐨', colorClass: 'bg-stone-500', phonetic: '/koʊˈɑː.ləz/' },
    ],
  },
};

export const CATEGORY_ORDER: CategoryId[] = [
  'sport',
  'color',
  'fruit',
  'food',
  'drink',
  'dessert',
  'animal',
];

export const AVAILABLE_AVATARS = [
  { id: 'dog', emoji: '🐶', label: 'Puppy' },
  { id: 'cat', emoji: '🐱', label: 'Kitty' },
  { id: 'panda', emoji: '🐼', label: 'Panda' },
  { id: 'fox', emoji: '🦊', label: 'Fox' },
  { id: 'lion', emoji: '🦁', label: 'Lion' },
  { id: 'rabbit', emoji: '🐰', label: 'Bunny' },
  { id: 'frog', emoji: '🐸', label: 'Froggy' },
  { id: 'bear', emoji: '🐻', label: 'Bear' },
  { id: 'tiger', emoji: '🐯', label: 'Tiger' },
  { id: 'koala', emoji: '🐨', label: 'Koala' },
  { id: 'star', emoji: '⭐', label: 'Star' },
  { id: 'rocket', emoji: '🚀', label: 'Rocket' },
];

export const AVAILABLE_COLORS = [
  { id: 'emerald', name: 'Emerald Green', hex: '#10b981', bgClass: 'bg-emerald-500', borderClass: 'border-emerald-500', textClass: 'text-emerald-600' },
  { id: 'sky', name: 'Sky Blue', hex: '#0284c7', bgClass: 'bg-sky-500', borderClass: 'border-sky-500', textClass: 'text-sky-600' },
  { id: 'indigo', name: 'Deep Indigo', hex: '#4f46e5', bgClass: 'bg-indigo-600', borderClass: 'border-indigo-600', textClass: 'text-indigo-600' },
  { id: 'rose', name: 'Vibrant Rose', hex: '#e11d48', bgClass: 'bg-rose-500', borderClass: 'border-rose-500', textClass: 'text-rose-600' },
  { id: 'amber', name: 'Sunny Amber', hex: '#d97706', bgClass: 'bg-amber-500', borderClass: 'border-amber-500', textClass: 'text-amber-600' },
  { id: 'purple', name: 'Royal Purple', hex: '#9333ea', bgClass: 'bg-purple-600', borderClass: 'border-purple-600', textClass: 'text-purple-600' },
  { id: 'teal', name: 'Fresh Teal', hex: '#0d9488', bgClass: 'bg-teal-500', borderClass: 'border-teal-500', textClass: 'text-teal-600' },
  { id: 'orange', name: 'Bright Orange', hex: '#ea580c', bgClass: 'bg-orange-500', borderClass: 'border-orange-500', textClass: 'text-orange-600' },
];
